# Configuración del plugin CustomEnderChest
inventory-title: "Custom EnderChest"
default-lines: 1

# Database Configuration
database:
  mysql: false
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: ''

permissions:
  EnderChestBar:
    '1': "EnderChestBar.1"
    '2': "EnderChestBar.2"
    '3': "EnderChestBar.3"
    '4': "EnderChestBar.4"
    '5': "EnderChestBar.5"
    '6': "EnderChestBar.6"

messages:
  open: "&aEnderChest opened!"
  no-permission-open: "&cYou do not have permission to open your EnderChest."
  no-permission-view: "&cYou do not have permission to view EnderChests."
  no-permission-reload: "&cYou do not have permission to reload the configuration."
  view-usage: "&cUsage: /enderchest view "
  viewing: "&aViewing the EnderChest of &f%player%"
  viewing-own: "&aYou are viewing your EnderChest"
  no-enderchest-found: "&cCould not find the specified player's EnderChest."
  invalid-uuid: "&cInvalid player UUID."
  only-players: "&cThis command can only be used by players."
  config-reloaded: "&aConfiguration reloaded successfully."
  usage: "&cUsage: /enderchest <open|view|reload>"