name: CustomEnderChest
version: '${project.version}'
main: org.dark.customenderchest.CustomEnderChest
api-version: '1.20'
commands:
  enderchest:
    description: Manage your custom enderchest
    aliases: [ec, echest, enc]
    permission: enderchest.use