name: CustomEnderChest
version: '${project.version}'
main: org.dark.customenderchest.CustomEnderChest
api-version: '1.21'
load: STARTUP
commands:
  enderchest:
    description: Comando para gestionar el EnderChest.
    permission: EnderChestBar.open