name: CustomEnderChest
version: '${project.version}'
main: org.dark.customenderchest.CustomEnderChest
api-version: '1.20'
commands:
  enderchest:
    description: Comando para gestionar el EnderChest.
    aliases: [ec]